### ISSUE TITLE
gift shop toevoegen als component?

### ISSUE THREAD

**Issue by ManoukK** [Mokerstier/Rijksmuseum-Ticketflow#17]
Vragen en punten die we moeten overwegen voor deze issue:
- Is dit echt nodig? Maakt dit de flow niet ingewikkelder?
- Waar plaatsen we dit?
- Hoe plaatsen we dit? Hoe gaat deze component eruit zien?
- Hoe gaat dit werken met de rest van de flow? (bijvoorbeeld bij de bestellingen lijst)

**Comment by MohamadAlGhorani** [comment]
Ik zie nu dat doneren is eruit gehaald van de Q42 online test versie dus ik denk dat we het gift shop niet hoeven te doen omdat we ook geen data hebben over het gift shop. Daarnaast als Q42 het niet erin hebben hoeven we het niet te doen denk ik.
