### ISSUE TITLE
(Is dit onze taak?) Skip button beter bij de navigatie knop

### ISSUE THREAD

**Issue by ManoukK** [Mokerstier/Rijksmuseum-Ticketflow#20]
Bij de screen reader test was de skip button bij de navigatie knop heel inconsistent. In de wiki staat meer informatie hierover

**Comment by MohamadAlGhorani** [comment]
we kunnen natuurlijk aangeven bij Q42 dat het niet goed gaat met hun header nav met screen reader. en we maken hier onze eigen header die goed werkt met screen reader f we doen helemaal geen header dan hebben we het probleem niet en ligt het dan bij hun.

**Comment by ManoukK** [comment]
nee gaan we niet doen
